########################################################################################
# -    ____ _       _           _  ____ _           _ _                              - #
# -   / ___| | ___ | |__   __ _| |/ ___| |__   __ _| | | ___ _ __   __ _  ___  ___   - #
# -  | |  _| |/ _ \| '_ \ / _` | | |   | '_ \ / _` | | |/ _ \ '_ \ / _` |/ _ \/ __|  - #
# -  | |_| | | (_) | |_) | (_| | | |___| | | | (_| | | |  __/ | | | (_| |  __/\__ \  - #
# -   \____|_|\___/|_.__/ \__,_|_|\____|_| |_|\__,_|_|_|\___|_| |_|\__, |\___||___/  - #
# -                                                                |___/             - #
# -  Author: Adr3ez_
# -
# -  Description:
# -
# -  Support:
# -
# -  Github:
# -
# -
########################################################################################
