##########################################################################################
# |-    ____ _       _           _  ____ _           _ _                              -| #
# |-   / ___| | ___ | |__   __ _| |/ ___| |__   __ _| | | ___ _ __   __ _  ___  ___   -| #
# |-  | |  _| |/ _ \| '_ \ / _` | | |   | '_ \ / _` | | |/ _ \ '_ \ / _` |/ _ \/ __|  -| #
# |-  | |_| | | (_) | |_) | (_| | | |___| | | | (_| | | |  __/ | | | (_| |  __/\__ \  -| #
# |-   \____|_|\___/|_.__/ \__,_|_|\____|_| |_|\__,_|_|_|\___|_| |_|\__, |\___||___/  -| #
# |-                                                                |___/             -| #
# |-  Author: Adr3ez_                                                                 -| #
# |-                                                                                  -| #
# |-  Wiki & Support: https://darklabs.gitbook.io/globalchallenges/                   -| #
# |-                                                                                  -| #
# |-  Github: https://github.com/Adreez/GlobalChallenges                              -| #
# |-                                                                                  -| #
##########################################################################################

# Please do not change! Unless developer told you to do so.
file-version: 1

##########################################################################################
# |-                                                                                  -| #
# |- STORAGE                                                                          -| #
# |-  » Types of storage: MySQL, SQLite                                               -| #
# |-                                                                                  -| #
##########################################################################################

storage:
  method: SQLite

  # Mysql setup
  data:
    hostname: "localhost"
    database: "globalchallenges"
    username: "root"
    password: ""

    minimumConnections: 1
    maximumConnections: 20
    connectionTimeout: 2000


##########################################################################################
# |-                                                                                  -| #
# |- PLUGIN SETTINGS                                                                  -| #
# |-  » Channge settings of all important things in plugin                            -| #
# |-                                                                                  -| #
##########################################################################################

settings:

  # How many players are required to start a challenge.
  players_required: 2

  # If placed blocks should be monitored for player_placed condition in challenges
  monitor_blocks: false

##########################################################################################
# |-                                                                                  -| #
# |- MESSAGES & SOUNDS                                                                -| #
# |-  » All messages are formatted using MiniMessage                                  -| #
# |-  » You can find docs at: https://docs.advntr.dev/minimessage/format.html         -| #
# |-                                                                                  -| #
# |-  » Legacy colors such as '&l' are NOT supported!                                 -| #
# |-                                                                                  -| #
##########################################################################################

messages:

  # In this category you can find all broadcast messages such as:
  # game_start, game_end
  broadcast:

    # In this category you can find all messages that will show when game will start.
    game_start:
      # This message will show in chat when challenge will start!
      # Possible placeholders: %name%, %description%, %key%
      chat:
        - ""
        - "                       <gradient:#245A6A:#D48C93><b>ɢʟᴏʙᴀʟᴄʜᴀʟʟᴇɴɢᴇs</b></gradient>"
        - "                   <gradient:#ff57fa:#ff00f7><obf>|||</obf> <u>ᴄʜᴀʟʟᴇɴɢᴇ ʜᴀs sᴛᴀʀᴛᴇᴅ</u> <obf>|||</obf></gradient>"
        - ""
        - " <dark_gray>» <#D48C93>Challenge <dark_gray>• <green>%name%"
        - ""
        - "                   <hover:show_text:'%description%'> <dark_gray>[<#2bffc0>information<dark_gray>] </hover>  <dark_gray>•  <hover:show_text:'<gray><i>Click to join the challenge!'><click:run_command:'/glch join'> <dark_gray>[<#00ff08>join<dark_gray>] </click></hover>"
        - ""
      # Title that will show when challenge starts
      title:
        title: "<gradient:#245A6A:#D48C93><b>ɢʟᴏʙᴀʟᴄʜᴀʟʟᴇɴɢᴇs</b></gradient>"
        subtitle: "<#00ff08><u>Join in chat!</u>"

        # In milliseconds (1 second = 1000 milliseconds)
        fadein: 500
        stay: 3000
        fadeout: 500
  player:
    active_bossbar: "<dark_grey>•|• <grey>(Time left) <color:#d6ff7d><time_left></color> <dark_grey>•|• <gradient:#245A6A:#D48C93><b>ɢʟᴏʙᴀʟᴄʜᴀʟʟᴇɴɢᴇs</b></gradient> <dark_grey>•|• <color:#d6ff7d><score></color> <grey>(score) <dark_grey>•|• "